apiVersion: v1
kind: ConfigMap
metadata:
  name: ovpn-configs
  labels:
{{ toYaml .Values.commonLabels | indent 4 }}
data:
  server.conf: |
    port 1194
    proto udp
    dev tun

    ca    /etc/openvpn/ca.crt
    cert  /etc/openvpn/server.crt
    key   /etc/openvpn/server.key
    dh    /etc/openvpn/dh.pem

    server 10.8.0.0 255.255.255.0

    ifconfig-pool-persist ipp.txt

    push "redirect-gateway def1 bypass-dhcp"
    push "dhcp-option DNS 208.67.222.222"
    push "dhcp-option DNS 208.67.220.220"

    duplicate-cn

    keepalive 10 120

    cipher AES-256-GCM
    ncp-ciphers AES-256-GCM:AES-256-CBC
    auth SHA512

    user nobody
    group nobody
    persist-key
    persist-tun

    status openvpn-status.log

    verb 1

    ; tls-server
    ; tls-version-min 1.2
    ; tls-auth /etc/openvpn/ta.key 0

    # domain to pass throw VPN
    push "route meduza.io vpn_gateway"

  client.ovpn: |
    client
    dev tun
    proto udp

    resolv-retry infinite

    nobind
    persist-key
    persist-tun

    cipher AES-256-GCM
    auth SHA512

    verb 3

    ;tls-client
    ;tls-version-min 1.2
    ;key-direction 1
    ;remote-cert-tls server
    ;ca ca.crt
    ;cert client.crt
    ;key client.key
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ovpn-vars
  labels:
{{ toYaml .Values.commonLabels | indent 4 }}
data:
  vars: |
    if [ -z "$EASYRSA_CALLER" ]; then
      echo "You appear to be sourcing an Easy-RSA 'vars' file." >&2
      echo "This is no longer necessary and is disallowed. See the section called" >&2
      echo "'How to use this file' near the top comments for more details." >&2
      return 1
    fi

    set_var EASYRSA_REQ_COUNTRY   "RU"
    set_var EASYRSA_REQ_PROVINCE  "Moscow"
    set_var EASYRSA_REQ_CITY      "Moscow"
    set_var EASYRSA_REQ_ORG       "NA"
    set_var EASYRSA_REQ_EMAIL     "dummy@box.com"
    set_var EASYRSA_REQ_OU        "Community"

    set_var EASYRSA_ALGO    "ec"
    set_var EASYRSA_DIGEST  "sha256"
